-- 코드를 작성해주세요
WITH CTE AS (
    SELECT P.ID FROM ECOLI_DATA P
        JOIN ECOLI_DATA C ON (P.PARENT_ID = C.ID AND C.PARENT_ID IS NULL)
)

SELECT P.ID FROM ECOLI_DATA P
    JOIN CTE C ON (P.PARENT_ID = C.ID)
ORDER BY P.ID