-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT PARENT.ITEM_ID FROM ITEM_TREE PARENT
        LEFT JOIN ITEM_TREE CHILD ON PARENT.ITEM_ID = CHILD.PARENT_ITEM_ID
    WHERE CHILD.ITEM_ID IS NULL
)
ORDER BY ITEM_ID DESC