-- 코드를 작성해주세요
WITH CTE AS (
    SELECT E.ID, COUNT(E.ID) AS CHILD_COUNT FROM ECOLI_DATA E LEFT JOIN
        ECOLI_DATA D ON (E.ID = D.PARENT_ID)
    WHERE D.PARENT_ID IS NOT NULL
    GROUP BY E.ID
)

SELECT D.ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT FROM ECOLI_DATA D
    LEFT JOIN CTE C ON (D.ID = C.ID)