-- 코드를 입력하세요
WITH CAR_INFO AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.END_DATE FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE REGEXP "SUV|세단"
    GROUP BY CAR_ID
    HAVING MAX(END_DATE) < "2022-11-01"
    ORDER BY C.CAR_ID
)
SELECT I.CAR_ID, I.CAR_TYPE,
    ROUND((I.DAILY_FEE - (I.DAILY_FEE * 0.01 * P.DISCOUNT_RATE)) * 30) AS FEE
    FROM CAR_INFO I
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON I.CAR_TYPE = P.CAR_TYPE
WHERE DURATION_TYPE LIKE "30%" AND
    ROUND((I.DAILY_FEE - (I.DAILY_FEE * 0.01 * P.DISCOUNT_RATE)) * 30) >= 500000 AND
    ROUND((I.DAILY_FEE - (I.DAILY_FEE * 0.01 * P.DISCOUNT_RATE)) * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC