-- 코드를 작성해주세요
WITH RANKING AS (
    SELECT ID, PERCENT_RANK() OVER (
        ORDER BY SIZE_OF_COLONY DESC
    ) SIZE_RANK FROM ECOLI_DATA
)
SELECT ID, CASE
            WHEN SIZE_RANK <= 0.25 THEN "CRITICAL"
            WHEN SIZE_RANK <= 0.5 THEN "HIGH"
            WHEN SIZE_RANK <= 0.75 THEN "MEDIUM"
            WHEN SIZE_RANK <= 1 THEN "LOW"
            END AS COLONY_NAME
    FROM RANKING
ORDER BY ID