-- 코드를 입력하세요
WITH TOTAL_USER AS (
    SELECT COUNT(USER_ID) AS TS FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)

SELECT YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(S.USER_ID)) / TS, 1) AS PURCHASED_RATIO
    FROM TOTAL_USER, USER_INFO I
    JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.JOINED LIKE "2021%"
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH