-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT P.ID, P.PARENT_ID, C.GENERATION + 1 AS GENERATION FROM ECOLI_DATA P
        JOIN CTE C ON (P.PARENT_ID = C.ID)
)

SELECT COUNT(*) AS COUNT, C.GENERATION FROM CTE C
    LEFT JOIN ECOLI_DATA CHILD ON CHILD.PARENT_ID = C.ID
WHERE CHILD.ID IS NULL
GROUP BY C.GENERATION
ORDER BY C.GENERATION