-- 코드를 입력하세요
WITH DATE AS (
    SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16"
)

SELECT DISTINCT(C.CAR_ID),
    IF(D.START_DATE IS NULL, "대여 가능", "대여중") AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
        LEFT JOIN DATE D ON C.CAR_ID = D.CAR_ID
ORDER BY C.CAR_ID DESC