-- 코드를 입력하세요
WITH JULY_INFO AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL FROM JULY
    GROUP BY FLAVOR
),

RESULT AS (
    SELECT I.FLAVOR, (TOTAL_ORDER + JULY_TOTAL) AS TOTAL_RESULT FROM FIRST_HALF H
        JOIN JULY_INFO I ON H.FLAVOR = I.FLAVOR
)

SELECT FLAVOR FROM RESULT
ORDER BY TOTAL_RESULT DESC
LIMIT 3