-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE
    WHERE HOUR < 23
)

SELECT CTE.HOUR, IFNULL(TEMP.HOUR_CNT, 0) FROM CTE
    LEFT JOIN (
        SELECT HOUR(DATETIME) AS HOUR,
        COUNT(HOUR(DATETIME)) AS HOUR_CNT FROM ANIMAL_OUTS
        GROUP BY HOUR(DATETIME)
    ) AS TEMP ON CTE.HOUR = TEMP.HOUR