-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM DEVELOPERS D
WHERE D.ID IN (
    SELECT D.ID FROM DEVELOPERS D
        JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE
    WHERE CATEGORY = "Front End"
)
ORDER BY D.ID