-- 코드를 입력하세요
WITH MOST_REVIEWER AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_COUNT FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)
SELECT P.MEMBER_NAME, R.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
    FROM REST_REVIEW R
    JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID FROM MOST_REVIEWER)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT