WITH CTE AS (
    SELECT T.ITEM_ID FROM ITEM_INFO I
        LEFT JOIN ITEM_TREE T ON (I.ITEM_ID = T.PARENT_ITEM_ID)
    WHERE I.RARITY = "RARE" AND T.PARENT_ITEM_ID IS NOT NULL
)

SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID FROM CTE
)
ORDER BY ITEM_ID DESC