-- 코드를 작성해주세요
WITH CTE AS (
    SELECT P.ID AS CHILD_ID, C.GENOTYPE FROM ECOLI_DATA P
        LEFT JOIN ECOLI_DATA C ON (P.PARENT_ID = C.ID)
    WHERE C.GENOTYPE IS NOT NULL AND (P.GENOTYPE & C.GENOTYPE = C.GENOTYPE)
)

SELECT C.CHILD_ID AS ID, D.GENOTYPE, C.GENOTYPE AS PARENT_GENOTYPE FROM CTE C
    JOIN ECOLI_DATA D ON (C.CHILD_ID = D.ID)
ORDER BY C.CHILD_ID