-- 코드를 입력하세요
WITH DATE AS (
    SELECT MONTH(START_DATE) MONTH, CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
),

CAR AS (
    SELECT CAR_ID FROM DATE
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS FROM DATE
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC