-- 코드를 작성해주세요
WITH CTE AS (
    SELECT D.ID FROM DEVELOPERS D LEFT JOIN SKILLCODES S
        ON (S.CODE & D.SKILL_CODE != 0)
    WHERE S.NAME = "Python" OR S.NAME = "C#"
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE ID IN (
    SELECT ID FROM CTE
)
ORDER BY ID