-- 코드를 입력하세요
WITH SALES_SUM AS (
    SELECT BOOK_ID, SUM(SALES) AS ID_TOTAL FROM BOOK_SALES
    WHERE SALES_DATE LIKE "2022-01%"
    GROUP BY BOOK_ID
)

SELECT CATEGORY, SUM(ID_TOTAL) AS TOTAL_SALES FROM BOOK B
    JOIN SALES_SUM S ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY