-- 코드를 작성해주세요
WITH FISH_LENGTH AS (
    SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT COUNT(FISH_TYPE) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE FROM FISH_LENGTH
    WHERE AVG_LENGTH >= 33
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE